You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

class Solution {
    public char findTheDifference(String s, String t) {
        int n=s.length();
        int m=t.length();
        int i=0;
        int ans=0;
        for(i=0;i<n;i++){
            ans^=s.charAt(i)^t.charAt(i);
        }
        if(i<m){
            ans^=t.charAt(i);
        }

        return (char)ans;
        
    }
}